using System.IO;
using System.Reflection.Emit;
using System.Windows;
using PolynomialLib;
using PolynomialLib.ReportGeneration;

namespace PolynomialSolverWpfApp
{
    /// <summary>
    /// Interaction logic for WindowShowReport.xaml
    /// </summary>
    public partial class WindowShowReport : Window
    {
        private readonly PolynomialFacade facade = PolynomialFacade.GetInstance();
        private string _savedPath;
        AbstractGenerator _generator;

        public WindowShowReport(string savedPath, AbstractGenerator generatingMethod)
        {
            _savedPath = savedPath;
            _generator = generatingMethod;

            InitializeComponent();
            InitializeAndNavigate();
        }

        // WebView2 потребує асинхронної ініціалізації
        private async void InitializeAndNavigate()
        {
            await ReportViewer.EnsureCoreWebView2Async(null);

            if (File.Exists(_savedPath))
            {
                ReportViewer.CoreWebView2.Navigate(_savedPath);
            }
            else
            {
                MessageBox.Show($"File not found: {_savedPath}");
            }
        }

        private void Button_Save_Click(object sender, RoutedEventArgs e)
        {
            Microsoft.Win32.SaveFileDialog dlg = new();

            string extension = Path.GetExtension(_savedPath).ToLower();

            if (extension == ".pdf")
            {
                dlg.Filter = "PDF Files (*.pdf)|*.pdf|All Files (*.*)|*.*";
                dlg.DefaultExt = ".pdf";
            }
            else
            {
                dlg.Filter = "HTML Files (*.html)|*.html|All Files (*.*)|*.*";
                dlg.DefaultExt = ".html";
            }

            dlg.FileName = Path.GetFileName(_savedPath);

            if (dlg.ShowDialog() == true)
            {
                try
                {
                    facade.GenerateReport(_generator, fileName: dlg.FileName, autoGeneratedPath: false);
                    MessageBox.Show("Report saved successfully!");
                }
                catch (Exception ex)
                {
                    MessageBox.Show($"Error saving file: {ex.Message}");
                }
            }
        }

        private void Button_Close_Click(object sender, RoutedEventArgs e)
        {
            facade.DeleteFile(_savedPath);
            Close();
        }
    }
}
