using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using PolynomialLib.DataManager;

namespace PolynomialLib.ReportGeneration
{
    public class HtmlGenerator : AbstractGenerator
    {
        private const string DEFAULT_NAME = "HtmlReport";
        ReportModel model;

        public HtmlGenerator(ReportModel model)
        {
            this.model = model;
        }

        /// <summary>
        /// Create unique path for report to be saved
        /// </summary>
        /// <param name="path">folder path</param>
        /// <param name="fileName">file name</param>
        /// <param name="autoGeneratedPath">whether unexisting folders will be genereted automaticaly</param>
        /// <returns>full path to created file</returns>
        protected override string Create(string path = null, string fileName = null, bool autoGeneratedPath = true)
        {
            string fullPath;
            if (path == null)
            {
                path = DEFAULT_PATH;
            }

            if (fileName == null)
            {
                fileName = DEFAULT_NAME;
            }

            fullPath = GetUniqueFullPath(path, fileName, ".html");

            PathManager.Create(fullPath, autoGeneratedPath);

            return fullPath;
        }

        public override string Generate(string path = null, string fileName = null, bool autoGeneratedPath = true)
        {
            var fullPath = Create(path, fileName, autoGeneratedPath);

            string htmlContent = BuildHtmlContent(model);

            try
            {
                File.WriteAllText(fullPath, htmlContent, Encoding.UTF8);
            }
            catch (Exception ex)
            {
                throw new Exception("Unable to perform this operation! HTML report can't be accessed");
            }

            return fullPath;
        }

        private string BuildHtmlContent(ReportModel model)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html lang=\"en\">");
            sb.AppendLine("<head>");
            sb.AppendLine("  <meta charset=\"UTF-8\">");
            sb.AppendLine("  <title>Equation Solving Report</title>");

            // CSS styles 
            sb.AppendLine("  <style>");
            sb.AppendLine("    body { font-family: Arial, sans-serif; margin: 30px; }");
            sb.AppendLine("    h1 { color: #333; }");
            sb.AppendLine("    h2 { color: #555; border-bottom: 1px solid #ccc; padding-bottom: 5px; }");
            sb.AppendLine("    .content-block { background-color: #f9f9f9; border: 1px solid #ddd; padding: 15px; margin-bottom: 20px; }");
            sb.AppendLine("    code { font-family: Consolas, monospace; background-color: #eee; padding: 2px 5px; }");
            sb.AppendLine("  </style>");

            sb.AppendLine("</head>");
            sb.AppendLine("<body>");

            // Document Body 
            sb.AppendLine("  <h1>Equation Solving Report</h1>");

            // f(x) Block 
            sb.AppendLine("  <div class=\"content-block\">");
            sb.AppendLine("    <h2>Input Data: f(x)</h2>");
            string f_text = "f(x) = " + model.F_Coefficients;
            sb.AppendLine("    <p><code>" + f_text + "</code></p>");
            sb.AppendLine("  </div>");

            // g(x) Block 
            sb.AppendLine("  <div class=\"content-block\">");
            sb.AppendLine("    <h2>Input Data: g(x)</h2>");
            sb.AppendLine("    <p>Function g(x) is defined by points:</p>");
            sb.AppendLine("    <ul>");
            for (int i = 0; i < model.G_Coordinates.XYCoordinates.Count; i++)
            {
                sb.AppendLine($"      <li><code>{model.G_Coordinates.XYCoordinates[i]}</code></li>");
            }
            sb.AppendLine("    </ul>");
            sb.AppendLine("  </div>");

            // Results Block 
            sb.AppendLine("  <div class=\"content-block\">");
            sb.AppendLine("    <h2>Results: Found Roots</h2>");
            if (model.Roots.Any())
            {
                sb.AppendLine("    <ul>");
                foreach (var root in model.Roots)
                {
                    sb.AppendLine($"      <li><code>x = {root:F5}</code></li>");
                }
                sb.AppendLine("    </ul>");
            }
            else
            {
                sb.AppendLine("    <p>No roots were found in the given range.</p>");
            }
            sb.AppendLine("  </div>");

            sb.AppendLine("</body>");
            sb.AppendLine("</html>");

            return sb.ToString();
        }
    }
}
