using QuestPDF.Fluent;
using QuestPDF.Infrastructure;
using PolynomialLib.DataManager;

namespace PolynomialLib.ReportGeneration
{
    public class PdfGenerator : AbstractGenerator
    {
        private const string DEFAULT_NAME = "PdfReport";
        ReportModel model;

        public PdfGenerator(ReportModel model)
        {
            this.model = model;
        }

        /// <summary>
        /// Create unique path for report to be saved
        /// </summary>
        /// <param name="path">folder path</param>
        /// <param name="fileName">file name</param>
        /// <param name="autoGeneratedPath">whether unexisting folders will be genereted automaticaly</param>
        /// <returns>full path to created file</returns>
        protected override string Create(string path = null, string fileName = null, bool autoGeneratedPath = true)
        {
            string fullPath;
            if (path == null)
            {
                path = DEFAULT_PATH;
            }

            if (fileName == null)
            {
                fileName = DEFAULT_NAME;
            }

            fullPath = GetUniqueFullPath(path, fileName, ".pdf");

            PathManager.Create(fullPath, autoGeneratedPath);

            return fullPath;
        }

        /// <summary>
        /// Generete report in PDF format
        /// </summary>
        /// <param name="model">ReportModel model</param>
        /// <param name="path">folder path</param>
        /// <param name="fileName">file name</param>
        /// <param name="autoGeneratedPath">whether unexisting folders will be genereted automaticaly</param>
        /// <returns>Full path to created file</returns>
        public override string Generate(string path = null, string fileName = null, bool autoGeneratedPath = true)
        {
            QuestPDF.Settings.License = LicenseType.Community;

            var fullPath = Create(path, fileName, autoGeneratedPath);

            var document = new EquationReportDocument(model);

            document.GeneratePdf(fullPath);

            return fullPath;
        }
    }
}
