using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PolynomialLib.DataContainers;
using PolynomialLib.DataManager;
using PolynomialLib.MathematicalCore;
using PolynomialLib.ReportGeneration;

namespace PolynomialLib
{
    public class PolynomialFacade
    {
        private EquationData _equationData;

        private readonly XmlManager<EquationData> _xmlManager = new();

        public Polynomial FxFunction { get; private set; }
        public Polynomial GxFunction { get; private set; }
        public Coordinates Coordinates { get; private set; }
        public bool Solved { get; private set; }
        public List<double> Roots { get; private set; }

        public PolynomialFacade(EquationData equationData)
        {
            _equationData = equationData;
            FxFunction = equationData.FxCoefficients;
            Coordinates = equationData.GxCoordinates;
        }

        private Polynomial FindLagrangePolynomial()
        {
            LagrangePolynomialCalculator lagrangeCalculator = new(Coordinates);
            return lagrangeCalculator.Calculate();
        }

        /// <summary>
        /// Finds equation roots
        /// </summary>
        /// <returns></returns>
        public List<double> Solve(IRootFinder solvingMethod = null, IList<double> initialGuesses = null) // Strategy Pattern
        {
            if(solvingMethod == null)
            {
                solvingMethod = new TangentMethodCalculator(initialGuesses);
            }
            // calculate g(x)
            GxFunction = FindLagrangePolynomial();

            // fx - gx
            Polynomial newPolynomial = FxFunction - GxFunction;

            // find roots
            Roots = solvingMethod.FindRoots(newPolynomial);
            Solved = true;

            return Roots;
        }

        public string Results()
        {
            if(Solved)
            {
                return $"Equation roots: {string.Join(",", Roots)}";
            }
            else
            {
                return "Equation wasn't solved yet";
            }
        }

        public EquationData ReadFromXml(string fullPpath)
        {
            if (fullPpath == null)
            {
                throw new ArgumentNullException("Path can't be null!");
            }
            return _xmlManager.Read(fullPpath);
        }

        public void WriteToXml(string fullPpath)
        {
            if (fullPpath == null)
            {
                throw new ArgumentNullException("Path can't be null!");
            }
            _xmlManager.Write(_equationData, fullPpath);
        }

        public string GenerateReport(AbstractGenerator generatingMethod, string path = null, string fileName = null, bool autoGeneratedPath = true) // Strategy Pattern
        {
            return generatingMethod.Generate(path, fileName, autoGeneratedPath);
        }
    }
}
